version: "3.9"
services:
  mqtt-client:
    depends_on:
      - storagedb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-client
    hostname: mqtt-client
    ports:
      - "4444:4444"
      - "1883:1883"
    deploy:
      restart_policy:
        condition: on-failure

  storagedb:
    image: influxdb:latest
    container_name: storagedb
    hostname: db
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      # Токен аутентификации для связи с начальным суперпользователем системы. Если не установлен, токен будет автоматически сгенерирован системой.
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    ports:
      - "8086:8086"
    volumes:
      - influxdb2:/var/lib/influxdb2:rw
      # - influxdb2-config:/etc/influxdb2
      # - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf
    deploy:
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - storagedb
    #environment:
      #- GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      #- GF_AUTH_ANONYMOUS_ENABLED=true
      #- GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  influxdb2:
  grafana-storage: